#!/usr/bin/env python3
"""Energy budget + two-tier BOM for Sec. 5 "What a deployed unit costs", derived ONLY from measured
rows (ICRA_2027/device_results/pipeline_power.tsv shelly_W_mean, or device_wall_meter.tsv means).
Formulas: E_day = 24 * P_avg; W_pv = E_day / (PSH * DERATE); C_batt = AUTONOMY_D * E_day / DOD.
Prints one row per measured (board, scenario) + a LaTeX table -> results/deployment_budget.tex.
Prices are INDICATIVE, dated PRICES_DATE, for the paper's supplement BOM. Constants below, no CLI args."""
import csv
import os

HERE = os.path.dirname(os.path.abspath(__file__))
OUT_TEX = os.path.join(HERE, "results", "deployment_budget.tex")
PSH = 4.0          # peak sun hours/day, temperate coast summer design point (state in the caption)
DERATE = 0.70      # panel-to-battery system efficiency (dirt, angle, controller, temperature)
AUTONOMY_D = 2.5   # cloudy-day buffer
DOD = {"LFP": 0.8, "AGM": 0.5}
PRICES_DATE = "2026-09"
# indicative EU prices for the supplement BOM (EUR); tiers pick components, sizing comes from the rows
BOM = {
    "budget": {"controller": ("PWM 10 A", 15), "battery_per_Wh": ("AGM 12 V", 0.15), "panel_per_W": ("rigid poly", 0.9),
               "power_conv": ("12->5 V buck 5 A", 12), "enclosure": ("IP65 box + gland", 35), "chem": "AGM"},
    "ideal": {"controller": ("Victron SmartSolar MPPT 75/10", 60), "battery_per_Wh": ("LiFePO4 12.8 V", 0.45),
              "panel_per_W": ("rigid mono", 1.1), "power_conv": ("12 V->USB-C PD 45 W", 25),
              "enclosure": ("marine IP66 + mast mount", 90), "chem": "LFP"},
}


CAMERA_TSV = os.path.join(HERE, "results", "camera_policy_rows.tsv")   # make_camera_policy_table.py (whole-unit windows)
BOARD_LABEL = {"orin": "Orin (7 W) + USB cam", "pi4_heatsink": "RPi 4 heatsink + USB cam", "pi4_bare": "RPi 4 bare + USB cam",
               "pi5": "RPi 5 + USB cam", "nano": "Jetson Nano 2019 + USB cam", "nxp": "i.MX95 Pro + USB cam", "frdm": "i.MX95 FRDM + USB cam"}


def rows():
    """Design point = the classifier-gated (cascade) whole-unit window per board and scene (no-rip = typical day, rip = upper
    bracket); gross wall W including the PSU and the camera."""
    out = []
    if os.path.isfile(CAMERA_TSV):
        for r in csv.DictReader(open(CAMERA_TSV), delimiter="\t"):
            if r["policy"] == "cascade":
                out.append((BOARD_LABEL.get(r["board"], r["board"]), f"gated, {r['scene']} replay", float(r["mean_W"]), "camera_policy_rows.tsv"))
    return out


def main():
    rs = rows()
    if not rs:
        print("no measured power rows yet (pipeline_power.tsv / device_wall_meter.tsv) - nothing to size")
        return
    os.makedirs(os.path.dirname(OUT_TEX), exist_ok=True)
    with open(OUT_TEX, "w") as f:
        f.write(f"% generated by deployment_budget.py; PSH={PSH}, derate={DERATE}, autonomy={AUTONOMY_D} d, prices {PRICES_DATE}\n")
        f.write("\\begin{tabular}{l l r r r r r}\\toprule\n")
        f.write("board & scenario & $\\bar P$ (W) & Wh/day & panel (W) & battery (Wh) & BOM (EUR) \\\\ \\midrule\n")
        for board, scen, p_avg, src in rs:
            e_day = 24 * p_avg
            w_pv = e_day / (PSH * DERATE)
            for tier, c in BOM.items():
                c_batt = AUTONOMY_D * e_day / DOD[c["chem"]]
                cost = (c["controller"][1] + c_batt * c["battery_per_Wh"][1] + w_pv * c["panel_per_W"][1]
                        + c["power_conv"][1] + c["enclosure"][1])
                print(f"{board:28s} {scen:28s} {p_avg:5.2f} W -> {e_day:6.1f} Wh/d, panel {w_pv:5.0f} W, "
                      f"batt {c_batt:6.0f} Wh ({c['chem']}), {tier} BOM ~{cost:4.0f} EUR  [{src}]")
                f.write(f"{board} & {scen} ({tier}) & {p_avg:.2f} & {e_day:.0f} & {w_pv:.0f} & {c_batt:.0f} & {cost:.0f} \\\\\n")
        f.write("\\bottomrule\\end{tabular}\n")
    print("->", OUT_TEX)


if __name__ == "__main__":
    main()
